//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demid
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class supportDBEntities : DbContext
    {
        public supportDBEntities()
            : base("name=supportDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Журналы_логов> Журналы_логов { get; set; }
        public virtual DbSet<История_действий> История_действий { get; set; }
        public virtual DbSet<Категории_проблем> Категории_проблем { get; set; }
        public virtual DbSet<Оборудование> Оборудование { get; set; }
        public virtual DbSet<Ответственные> Ответственные { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Помещения_и_оборудование> Помещения_и_оборудование { get; set; }
        public virtual DbSet<Решения> Решения { get; set; }
        public virtual DbSet<Статусы_тикетов> Статусы_тикетов { get; set; }
        public virtual DbSet<Тикеты> Тикеты { get; set; }
    }
}
