//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Журналы_логов
    {
        public int Идентификатор { get; set; }
        public Nullable<int> Идентификатор_тикета { get; set; }
        public string Содержание_лога { get; set; }
        public string Уровень_важности { get; set; }
        public Nullable<System.DateTime> Дата_и_время { get; set; }
    
        public virtual Тикеты Тикеты { get; set; }
    }
}
