//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оборудование
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Оборудование()
        {
            this.Помещения_и_оборудование = new HashSet<Помещения_и_оборудование>();
        }
    
        public int Идентификатор { get; set; }
        public string Название { get; set; }
        public string Серийный_номер { get; set; }
        public string Описание { get; set; }
        public Nullable<System.DateTime> Дата_покупки { get; set; }
        public Nullable<System.DateTime> Гарантийный_срок { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Помещения_и_оборудование> Помещения_и_оборудование { get; set; }
    }
}
